=== akarisoho/jsp-servlet/introduce-xml/my_intro.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE intro[
	<!NOTATION jpeg PUBLIC "image/jpeg" "mspaint.exe">
	<!ELEMENT image EMPTY>
	<!ATTLIST image src CDATA #REQUIRED type NOTATION (jpeg) #REQUIRED>
	
	<!ELEMENT intro(block1,block2,block3,block4,block5,block6,block7)>
	<!ELEMENT block1 (studentID,name,major,grade,gender,address)>
	<!ELEMENT block2 (company,department,main_task)>
	<!ELEMENT block3 (reson,expectation,wish)>
	<!ELEMENT block4 (advantages,disadvantages)>
	<!ELEMENT block5 (#PCDATA)>
	<!ELEMENT block6 (#PCDATA)>
	<!ELEMENT block7 (#PCDATA)>
	
	<!ELEMENT studentID (#PCDATA)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT major (#PCDATA)>
	<!ELEMENT grade (#PCDATA)>
	<!ELEMENT gender (#PCDATA)>
	<!ELEMENT address (#PCDATA)>
	
	<!ELEMENT company (#PCDATA)>
	<!ELEMENT department (#PCDATA)>
	<!ELEMENT main_task (#PCDATA)>

	<!ELEMENT reson (#PCDATA)>
	<!ELEMENT expectation (#PCDATA)>
	<!ELEMENT wish (#PCDATA)>

	<!ELEMENT adventeges (#PCDATA)>
	<!ELEMENT disadvantages (#PCDATA)>
]>

=== akarisoho/jsp-servlet/introduce-xml/my_intro.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="intro.css" type="text/css"?>
<!DOCTYPE intro SYSTEM "my_intro.dtd">

<intro>	
	<!-- 1.학번, 성명, 소속학과, 학년, 성별, 거주지역(시) -->
	<block1>
		<studentID>학번 : 2021</studentID>
		<name>성명 : 별이구르미</name>
		<major>소속학과 : 응용소프트웨어학과</major>
		<grade>학년 : 3학년</grade>
		<gender>성별 : 여자</gender>
		<address>거주지역(시) : 서울시</address>
	</block1>
	
	<!-- 2.소속회사, 부서, 주된 업무 -->
	<block2>
		<company>소속회사 : 지율출판사</company>
		<department>부서 : 없음</department>
		<main_task>주업무 : 콘텐츠 개발 및 제작, 웹 구축/유지보수</main_task>
	</block2>
	
	<block3>
		<reson>지원동기 : 웹 개발이라는 파는 끊임없이 성장해 나갈 수 있는 직업군이라고 생각합니다.</reson>
		<expectation>기대 : 원활한 커뮤니케이션을 통한 성공</expectation>
		<wish>바람 : 함께 발전하기!</wish>
	</block3>
	
	<block4>
		<advantages>장점 : 겸손한 자세로 열의를 가지고 주어진 일을 함</advantages>
		<disadvantages>강점 : 아이디어 내는 것을 즐김 </disadvantages>
	</block4>
	
	<block5> 직업을 바꾸고자할 때면 늘 "그 나이에 이미 늦었어"라는 말을 종종 들었지만,<br/>
그 말을 듣고 다른 직업에 도전하지 않았다면, <br/>
이렇게 흥미로운 일들을.. 각 직업군에서 느끼는 보람을 경험해 보지 못했을 것입니다.<br/>
그래서 전 이번에도 도전해 봅니다.</block5>
</intro>
